### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by alex-hedley** [alex-hedley/ocaml-example#1]
- [Bisect_ppx](https://github.com/aantron/bisect_ppx#bisect_ppx--)
  - [Bisect_ppx](https://github.com/aantron/bisect_ppx) is a code coverage tool for OCaml and Reason. It helps you test thoroughly by showing what's not tested.

**Comment by alex-hedley** [comment]
See `https://github.com/aantron/bisect_ppx/issues/411`

```yaml
      - name: Run tests
        run: |
             mkdir $BISECT_DIR
             opam exec -- dune runtest --instrument-with bisect_ppx
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          BISECT_FILE: ${{ runner.temp }}/_bisect_ppx_data/data

      - name: Send coverage report to Coveralls
        run: opam exec -- bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
```

**Comment by alex-hedley** [comment]
```yaml
- name: 🧪 Test and Coverage
  run: "opam exec -- dune runtest --instrument-with bisect_ppx --force"
- name: 📄 Coverage Report"
  run: "opam exec -- bisect-ppx-report summary"
```
